import tkinter as tk
import Methods as m

window = tk.Tk()
window.geometry("1366x705")
window.title("Student Management System")

Label_School = tk.Label()
Label_School.place(relx=0.0, rely=0.0, height=60, width=1358)
Label_School.configure(background="#000000")
Label_School.configure(borderwidth="4")
Label_School.configure(disabledforeground="#a3a3a3")
Label_School.configure(font="-family {OCR A Std} -size 14 -weight bold")
Label_School.configure(foreground="#ffffff")
Label_School.configure(text='''ST. Thomas' College, Matale''')

Left_Student_Information = tk.LabelFrame()
Left_Student_Information.place(relx=0.004, rely=0.099, relheight=0.716, relwidth=0.381)
Left_Student_Information.configure(relief='groove')
Left_Student_Information.configure(borderwidth="8")
Left_Student_Information.configure(font="-family {OCR A Std} -size 17 -weight bold -slant italic")
Left_Student_Information.configure(foreground="black")
Left_Student_Information.configure(text='''Student's Information''')
Left_Student_Information.configure(background="#fffafd")

Student_ID = tk.Label(Left_Student_Information)
Student_ID.place(relx=0.077, rely=0.119, height=37, width=160, bordermode='ignore')
Student_ID.configure(background="#9198d8")
Student_ID.configure(borderwidth="5")
Student_ID.configure(disabledforeground="#a3a3a3")
Student_ID.configure(font="-family {Segoe UI} -size 14")
Student_ID.configure(foreground="#000000")
Student_ID.configure(text='''Student's ID''')

Student_Name = tk.Label(Left_Student_Information)
Student_Name.place(relx=0.077, rely=0.297, height=31, width=160, bordermode='ignore')
Student_Name.configure(background="#9198d8")
Student_Name.configure(disabledforeground="#a3a3a3")
Student_Name.configure(font="-family {Segoe UI} -size 14")
Student_Name.configure(foreground="#000000")
Student_Name.configure(text='''Student's Name''')

Grade = tk.Label(Left_Student_Information)
Grade.place(relx=0.077, rely=0.475, height=31, width=160, bordermode='ignore')
Grade.configure(background="#9198d8")
Grade.configure(disabledforeground="#a3a3a3")
Grade.configure(font="-family {Segoe UI} -size 14")
Grade.configure(foreground="#000000")
Grade.configure(text='''Grade''')

Sex = tk.Label(Left_Student_Information)
Sex.place(relx=0.077, rely=0.653, height=31, width=160, bordermode='ignore')
Sex.configure(background="#9198d8")
Sex.configure(disabledforeground="#a3a3a3")
Sex.configure(font="-family {Segoe UI} -size 14")
Sex.configure(foreground="#000000")
Sex.configure(text='''Sex''')

Date_of_Birth = tk.Label(Left_Student_Information)
Date_of_Birth.place(relx=0.077, rely=0.832, height=31, width=160, bordermode='ignore')
Date_of_Birth.configure(background="#9198d8")
Date_of_Birth.configure(disabledforeground="#a3a3a3")
Date_of_Birth.configure(font="-family {Segoe UI} -size 14")
Date_of_Birth.configure(foreground="#000000")
Date_of_Birth.configure(text='''Date of Birth''')

Entry_Student_ID = tk.Entry(Left_Student_Information)
Entry_Student_ID.place(relx=0.442, rely=0.119, height=30, relwidth=0.488, bordermode='ignore')
Entry_Student_ID.configure(background="#9198d8")
Entry_Student_ID.configure(disabledforeground="#a3a3a3")
Entry_Student_ID.configure(font="-family {Segoe UI} -size 14")
Entry_Student_ID.configure(foreground="#000000")
Entry_Student_ID.configure(insertbackground="black")

Entry_Student_Name = tk.Entry(Left_Student_Information)
Entry_Student_Name.place(relx=0.442, rely=0.297, height=30, relwidth=0.488, bordermode='ignore')
Entry_Student_Name.configure(background="#9198d8")
Entry_Student_Name.configure(disabledforeground="#a3a3a3")
Entry_Student_Name.configure(font="-family {Segoe UI} -size 14")
Entry_Student_Name.configure(foreground="#000000")
Entry_Student_Name.configure(insertbackground="black")

Entry_Grade = tk.Entry(Left_Student_Information)
Entry_Grade.place(relx=0.442, rely=0.475, height=29, relwidth=0.488, bordermode='ignore')
Entry_Grade.configure(background="#9198d8")
Entry_Grade.configure(disabledforeground="#a3a3a3")
Entry_Grade.configure(font="-family {Segoe UI} -size 14")
Entry_Grade.configure(foreground="#000000")
Entry_Grade.configure(insertbackground="black")

Radiobutton_Sex_Female = tk.Radiobutton(Left_Student_Information)
Radiobutton_Sex_Female.place(relx=0.673, rely=0.653, relheight=0.059, relwidth=0.252, bordermode='ignore')
Radiobutton_Sex_Female.configure(activebackground="#ececec")
Radiobutton_Sex_Female.configure(activeforeground="#000000")
Radiobutton_Sex_Female.configure(background="#9198d8")
Radiobutton_Sex_Female.configure(disabledforeground="#a3a3a3")
Radiobutton_Sex_Female.configure(font="-family {Segoe UI} -size 14")
Radiobutton_Sex_Female.configure(foreground="#000000")
Radiobutton_Sex_Female.configure(highlightbackground="#d9d9d9")
Radiobutton_Sex_Female.configure(highlightcolor="black")
Radiobutton_Sex_Female.configure(justify='left')
Radiobutton_Sex_Female.configure(text='''Female''')
Radiobutton_Sex_Female.configure(variable= m.var,value= 2)
Radiobutton_Sex_Female.configure(command= m.female_selected)

Radiobutton_Sex_Male = tk.Radiobutton(Left_Student_Information)
Radiobutton_Sex_Male.place(relx=0.442, rely=0.653, relheight=0.059, relwidth=0.217, bordermode='ignore')
Radiobutton_Sex_Male.configure(activebackground="#ececec")
Radiobutton_Sex_Male.configure(activeforeground="#000000")
Radiobutton_Sex_Male.configure(background="#9198d8")
Radiobutton_Sex_Male.configure(disabledforeground="#a3a3a3")
Radiobutton_Sex_Male.configure(font="-family {Segoe UI} -size 14")
Radiobutton_Sex_Male.configure(foreground="#000000")
Radiobutton_Sex_Male.configure(highlightbackground="#d9d9d9")
Radiobutton_Sex_Male.configure(highlightcolor="black")
Radiobutton_Sex_Male.configure(justify='left')
Radiobutton_Sex_Male.configure(text='''Male''')
Radiobutton_Sex_Male.configure(variable= m.var,value= 1)
Radiobutton_Sex_Male.configure(command= m.male_selected)

Entry_Date = tk.Entry(Left_Student_Information, text="hi")
Entry_Date.place(relx=0.442, rely=0.832, relheight=0.059, relwidth=0.106, bordermode='ignore')
Entry_Date.configure(background="#9198d8")
Entry_Date.configure(disabledforeground="#a3a3a3")
Entry_Date.configure(font="-family {Segoe UI} -size 14")
Entry_Date.configure(foreground="black")
Entry_Date.configure(highlightbackground="black")
Entry_Date.configure(highlightcolor="black")
Entry_Date.configure(insertbackground="black")
Entry_Date.configure(selectbackground="#c4c4c4")
Entry_Date.configure(selectforeground="black")

Entry_Month = tk.Entry(Left_Student_Information)
Entry_Month.place(relx=0.577, rely=0.832, relheight=0.059, relwidth=0.125, bordermode='ignore')
Entry_Month.configure(background="#9198d8")
Entry_Month.configure(disabledforeground="#a3a3a3")
Entry_Month.configure(font="-family {Segoe UI} -size 14")
Entry_Month.configure(foreground="black")
Entry_Month.configure(highlightbackground="black")
Entry_Month.configure(highlightcolor="black")
Entry_Month.configure(insertbackground="black")
Entry_Month.configure(selectbackground="#c4c4c4")
Entry_Month.configure(selectforeground="black")

Entry_Year = tk.Entry(Left_Student_Information)
Entry_Year.place(relx=0.731, rely=0.832, relheight=0.059, relwidth=0.183, bordermode='ignore')
Entry_Year.configure(background="#9198d8")
Entry_Year.configure(disabledforeground="#a3a3a3")
Entry_Year.configure(font="-family {Segoe UI} -size 14")
Entry_Year.configure(foreground="black")
Entry_Year.configure(highlightbackground="black")
Entry_Year.configure(highlightcolor="black")
Entry_Year.configure(insertbackground="black")
Entry_Year.configure(selectbackground="#c4c4c4")
Entry_Year.configure(selectforeground="black")

Frame_right = tk.Frame()
Frame_right.place(relx=0.388, rely=0.099, relheight=0.901, relwidth=0.611)
Frame_right.configure(relief='groove')
Frame_right.configure(borderwidth="8")
Frame_right.configure(relief="groove")
Frame_right.configure(background="#d9d9d9")

listbox_left = tk.Listbox(Frame_right)
listbox_left.place(relx=0.012, rely=0.014, relheight=0.968, relwidth=0.480)
listbox_left.configure(background="black")
listbox_left.configure(disabledforeground="#a3a3a3")
listbox_left.configure(font="-family {Segoe UI} -size 14")
listbox_left.configure(foreground="white")
listbox_left.configure(highlightbackground="#d9d9d9")
listbox_left.configure(highlightcolor="black")

listbox_right = tk.Listbox(Frame_right)
listbox_right.place(relx=0.500, rely=0.014, relheight=0.968, relwidth=0.480)
listbox_right.configure(background="black")
listbox_right.configure(disabledforeground="#a3a3a3")
listbox_right.configure(font="-family {Segoe UI} -size 14")
listbox_right.configure(foreground="white")
listbox_right.configure(highlightbackground="#d9d9d9")
listbox_right.configure(highlightcolor="black")


Frame_Button = tk.Frame()
Frame_Button.place(relx=0.004, rely=0.823, relheight=0.163, relwidth=0.377)
Frame_Button.configure(relief='groove')
Frame_Button.configure(borderwidth="8")
Frame_Button.configure(relief="groove")
Frame_Button.configure(background="black")

Button_ADD = tk.Button(Frame_Button)
Button_ADD.place(relx=0.020, rely=0.348, height=40, width=80)
Button_ADD.configure(activebackground="#ececec")
Button_ADD.configure(activeforeground="#000000")
Button_ADD.configure(background="#b423d8")
Button_ADD.configure(borderwidth="5")
Button_ADD.configure(disabledforeground="#a3a3a3")
Button_ADD.configure(font="-family {Segoe UI} -size 14")
Button_ADD.configure(foreground="#000000")
Button_ADD.configure(highlightbackground="#d9d9d9")
Button_ADD.configure(highlightcolor="black")
Button_ADD.configure(pady="0")
Button_ADD.configure(text='''ADD''')
Button_ADD.configure(command=m.add_info)

Button_REFRESH = tk.Button(Frame_Button)
Button_REFRESH.place(relx=0.420, rely=0.348, height=40, width=85)
Button_REFRESH.configure(activebackground="#ececec")
Button_REFRESH.configure(activeforeground="#000000")
Button_REFRESH.configure(background="#b423d8")
Button_REFRESH.configure(borderwidth="5")
Button_REFRESH.configure(disabledforeground="#a3a3a3")
Button_REFRESH.configure(font="-family {Segoe UI} -size 14")
Button_REFRESH.configure(foreground="#000000")
Button_REFRESH.configure(highlightbackground="#d9d9d9")
Button_REFRESH.configure(highlightcolor="black")
Button_REFRESH.configure(pady="0")
Button_REFRESH.configure(text='''REFRESH''')
Button_REFRESH.configure(command=m.refresh_info)

Button_SEARCH = tk.Button(Frame_Button)
Button_SEARCH.place(relx=0.220, rely=0.348, height=40, width=85)
Button_SEARCH.configure(activebackground="#ececec")
Button_SEARCH.configure(activeforeground="#000000")
Button_SEARCH.configure(background="#b423d8")
Button_SEARCH.configure(borderwidth="5")
Button_SEARCH.configure(disabledforeground="#a3a3a3")
Button_SEARCH.configure(font="-family {Segoe UI} -size 14")
Button_SEARCH.configure(foreground="#000000")
Button_SEARCH.configure(highlightbackground="#d9d9d9")
Button_SEARCH.configure(highlightcolor="black")
Button_SEARCH.configure(pady="0")
Button_SEARCH.configure(text='''SEARCH''')
Button_SEARCH.configure(command=m.search_info)

Button_DELETE = tk.Button(Frame_Button)
Button_DELETE.place(relx=0.630, rely=0.348, height=40, width=80)
Button_DELETE.configure(activebackground="#ececec")
Button_DELETE.configure(activeforeground="#000000")
Button_DELETE.configure(background="#b423d8")
Button_DELETE.configure(borderwidth="5")
Button_DELETE.configure(disabledforeground="#a3a3a3")
Button_DELETE.configure(font="-family {Segoe UI} -size 14")
Button_DELETE.configure(foreground="#000000")
Button_DELETE.configure(highlightbackground="#d9d9d9")
Button_DELETE.configure(highlightcolor="black")
Button_DELETE.configure(pady="0")
Button_DELETE.configure(text='''DELETE''')
Button_DELETE.configure(command=m.delete_student)

Button_RESET = tk.Button(Frame_Button)
Button_RESET.place(relx=0.830, rely=0.348, height=40, width=80)
Button_RESET.configure(activebackground="#ececec")
Button_RESET.configure(activeforeground="#000000")
Button_RESET.configure(background="#b423d8")
Button_RESET.configure(borderwidth="5")
Button_RESET.configure(disabledforeground="#a3a3a3")
Button_RESET.configure(font="-family {Segoe UI} -size 14")
Button_RESET.configure(foreground="#000000")
Button_RESET.configure(highlightbackground="#d9d9d9")
Button_RESET.configure(highlightcolor="black")
Button_RESET.configure(pady="0")
Button_RESET.configure(text='''RESET''')
Button_RESET.configure(command=m.reset_info)
